// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appsettings.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppSettings struct {
	DaemonAddress        string   `protobuf:"bytes,1,opt,name=daemon_address,json=daemonAddress,proto3" json:"daemon_address,omitempty"`
	Theme                string   `protobuf:"bytes,2,opt,name=theme,proto3" json:"theme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppSettings) Reset()         { *m = AppSettings{} }
func (m *AppSettings) String() string { return proto.CompactTextString(m) }
func (*AppSettings) ProtoMessage()    {}
func (*AppSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_b07f0cbec9c308f4, []int{0}
}

func (m *AppSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppSettings.Unmarshal(m, b)
}
func (m *AppSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppSettings.Marshal(b, m, deterministic)
}
func (m *AppSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppSettings.Merge(m, src)
}
func (m *AppSettings) XXX_Size() int {
	return xxx_messageInfo_AppSettings.Size(m)
}
func (m *AppSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_AppSettings.DiscardUnknown(m)
}

var xxx_messageInfo_AppSettings proto.InternalMessageInfo

func (m *AppSettings) GetDaemonAddress() string {
	if m != nil {
		return m.DaemonAddress
	}
	return ""
}

func (m *AppSettings) GetTheme() string {
	if m != nil {
		return m.Theme
	}
	return ""
}

func init() {
	proto.RegisterType((*AppSettings)(nil), "model.AppSettings")
}

func init() { proto.RegisterFile("appsettings.proto", fileDescriptor_b07f0cbec9c308f4) }

var fileDescriptor_b07f0cbec9c308f4 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x2c, 0x28, 0x28,
	0x4e, 0x2d, 0x29, 0xc9, 0xcc, 0x4b, 0x2f, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd,
	0xcd, 0x4f, 0x49, 0xcd, 0x51, 0xf2, 0xe2, 0xe2, 0x76, 0x2c, 0x28, 0x08, 0x86, 0xca, 0x09, 0xa9,
	0x72, 0xf1, 0xa5, 0x24, 0xa6, 0xe6, 0xe6, 0xe7, 0xc5, 0x27, 0xa6, 0xa4, 0x14, 0xa5, 0x16, 0x17,
	0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xf1, 0x42, 0x44, 0x1d, 0x21, 0x82, 0x42, 0x22, 0x5c,
	0xac, 0x25, 0x19, 0xa9, 0xb9, 0xa9, 0x12, 0x4c, 0x60, 0x59, 0x08, 0x27, 0x89, 0x0d, 0x6c, 0xb2,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x67, 0xef, 0x99, 0x0f, 0x6e, 0x00, 0x00, 0x00,
}
