// Code generated by protoc-gen-go. DO NOT EDIT.
// source: change_name.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChangeNameParam struct {
	Filepath             string   `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeNameParam) Reset()         { *m = ChangeNameParam{} }
func (m *ChangeNameParam) String() string { return proto.CompactTextString(m) }
func (*ChangeNameParam) ProtoMessage()    {}
func (*ChangeNameParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_7876fe0286614443, []int{0}
}

func (m *ChangeNameParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeNameParam.Unmarshal(m, b)
}
func (m *ChangeNameParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeNameParam.Marshal(b, m, deterministic)
}
func (m *ChangeNameParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeNameParam.Merge(m, src)
}
func (m *ChangeNameParam) XXX_Size() int {
	return xxx_messageInfo_ChangeNameParam.Size(m)
}
func (m *ChangeNameParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeNameParam.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeNameParam proto.InternalMessageInfo

func (m *ChangeNameParam) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

type ChangeNameResult struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeNameResult) Reset()         { *m = ChangeNameResult{} }
func (m *ChangeNameResult) String() string { return proto.CompactTextString(m) }
func (*ChangeNameResult) ProtoMessage()    {}
func (*ChangeNameResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_7876fe0286614443, []int{1}
}

func (m *ChangeNameResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeNameResult.Unmarshal(m, b)
}
func (m *ChangeNameResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeNameResult.Marshal(b, m, deterministic)
}
func (m *ChangeNameResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeNameResult.Merge(m, src)
}
func (m *ChangeNameResult) XXX_Size() int {
	return xxx_messageInfo_ChangeNameResult.Size(m)
}
func (m *ChangeNameResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeNameResult.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeNameResult proto.InternalMessageInfo

func (m *ChangeNameResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*ChangeNameParam)(nil), "model.ChangeNameParam")
	proto.RegisterType((*ChangeNameResult)(nil), "model.ChangeNameResult")
}

func init() { proto.RegisterFile("change_name.proto", fileDescriptor_7876fe0286614443) }

var fileDescriptor_7876fe0286614443 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xce, 0x48, 0xcc,
	0x4b, 0x4f, 0x8d, 0xcf, 0x4b, 0xcc, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd,
	0xcd, 0x4f, 0x49, 0xcd, 0x51, 0xd2, 0xe5, 0xe2, 0x77, 0x06, 0xcb, 0xf9, 0x25, 0xe6, 0xa6, 0x06,
	0x24, 0x16, 0x25, 0xe6, 0x0a, 0x49, 0x71, 0x71, 0xa4, 0x65, 0xe6, 0xa4, 0x16, 0x24, 0x96, 0x64,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xf9, 0x4a, 0x5a, 0x5c, 0x02, 0x08, 0xe5, 0x41,
	0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x42, 0x62, 0x5c, 0x6c, 0xc5, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x50,
	0xd5, 0x50, 0x5e, 0x12, 0x1b, 0xd8, 0x22, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xa0,
	0x1e, 0xa9, 0x7d, 0x00, 0x00, 0x00,
}
