// Code generated by protoc-gen-go. DO NOT EDIT.
// source: change_password.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChangePasswordParam struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordParam) Reset()         { *m = ChangePasswordParam{} }
func (m *ChangePasswordParam) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordParam) ProtoMessage()    {}
func (*ChangePasswordParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e53f826de1b5ba2, []int{0}
}

func (m *ChangePasswordParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordParam.Unmarshal(m, b)
}
func (m *ChangePasswordParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordParam.Marshal(b, m, deterministic)
}
func (m *ChangePasswordParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordParam.Merge(m, src)
}
func (m *ChangePasswordParam) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordParam.Size(m)
}
func (m *ChangePasswordParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordParam.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordParam proto.InternalMessageInfo

func (m *ChangePasswordParam) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ChangePasswordResult struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResult) Reset()         { *m = ChangePasswordResult{} }
func (m *ChangePasswordResult) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResult) ProtoMessage()    {}
func (*ChangePasswordResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e53f826de1b5ba2, []int{1}
}

func (m *ChangePasswordResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResult.Unmarshal(m, b)
}
func (m *ChangePasswordResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResult.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResult.Merge(m, src)
}
func (m *ChangePasswordResult) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResult.Size(m)
}
func (m *ChangePasswordResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResult.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResult proto.InternalMessageInfo

func (m *ChangePasswordResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*ChangePasswordParam)(nil), "model.ChangePasswordParam")
	proto.RegisterType((*ChangePasswordResult)(nil), "model.ChangePasswordResult")
}

func init() { proto.RegisterFile("change_password.proto", fileDescriptor_2e53f826de1b5ba2) }

var fileDescriptor_2e53f826de1b5ba2 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xce, 0x48, 0xcc,
	0x4b, 0x4f, 0x8d, 0x2f, 0x48, 0x2c, 0x2e, 0x2e, 0xcf, 0x2f, 0x4a, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x32, 0xe4, 0x12, 0x76, 0x06, 0xcb, 0x07,
	0x40, 0xa5, 0x03, 0x12, 0x8b, 0x12, 0x73, 0x85, 0xa4, 0xb8, 0x38, 0x60, 0xea, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x25, 0x3d, 0x2e, 0x11, 0x54, 0x2d, 0x41, 0xa9, 0xc5, 0xa5,
	0x39, 0x25, 0x42, 0x62, 0x5c, 0x6c, 0xc5, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x50, 0x1d, 0x50, 0x5e,
	0x12, 0x1b, 0xd8, 0x42, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x95, 0x6b, 0x36, 0x43, 0x89,
	0x00, 0x00, 0x00,
}
