// Code generated by protoc-gen-go. DO NOT EDIT.
// source: check_password.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckPasswordParam struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPasswordParam) Reset()         { *m = CheckPasswordParam{} }
func (m *CheckPasswordParam) String() string { return proto.CompactTextString(m) }
func (*CheckPasswordParam) ProtoMessage()    {}
func (*CheckPasswordParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_061db27ede7ea8cf, []int{0}
}

func (m *CheckPasswordParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPasswordParam.Unmarshal(m, b)
}
func (m *CheckPasswordParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPasswordParam.Marshal(b, m, deterministic)
}
func (m *CheckPasswordParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPasswordParam.Merge(m, src)
}
func (m *CheckPasswordParam) XXX_Size() int {
	return xxx_messageInfo_CheckPasswordParam.Size(m)
}
func (m *CheckPasswordParam) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPasswordParam.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPasswordParam proto.InternalMessageInfo

func (m *CheckPasswordParam) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CheckPasswordResult struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPasswordResult) Reset()         { *m = CheckPasswordResult{} }
func (m *CheckPasswordResult) String() string { return proto.CompactTextString(m) }
func (*CheckPasswordResult) ProtoMessage()    {}
func (*CheckPasswordResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_061db27ede7ea8cf, []int{1}
}

func (m *CheckPasswordResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPasswordResult.Unmarshal(m, b)
}
func (m *CheckPasswordResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPasswordResult.Marshal(b, m, deterministic)
}
func (m *CheckPasswordResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPasswordResult.Merge(m, src)
}
func (m *CheckPasswordResult) XXX_Size() int {
	return xxx_messageInfo_CheckPasswordResult.Size(m)
}
func (m *CheckPasswordResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPasswordResult.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPasswordResult proto.InternalMessageInfo

func (m *CheckPasswordResult) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *CheckPasswordResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckPasswordParam)(nil), "model.CheckPasswordParam")
	proto.RegisterType((*CheckPasswordResult)(nil), "model.CheckPasswordResult")
}

func init() { proto.RegisterFile("check_password.proto", fileDescriptor_061db27ede7ea8cf) }

var fileDescriptor_061db27ede7ea8cf = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xce, 0x48, 0x4d,
	0xce, 0x8e, 0x2f, 0x48, 0x2c, 0x2e, 0x2e, 0xcf, 0x2f, 0x4a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x32, 0xe0, 0x12, 0x72, 0x06, 0x49, 0x07, 0x40,
	0x65, 0x03, 0x12, 0x8b, 0x12, 0x73, 0x85, 0xa4, 0xb8, 0x38, 0x60, 0xca, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0xe0, 0x7c, 0x25, 0x67, 0x2e, 0x61, 0x14, 0x1d, 0x41, 0xa9, 0xc5, 0xa5, 0x39,
	0x25, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0x99, 0x10, 0xf5, 0x1c, 0x41, 0x10, 0x8e, 0x90,
	0x18, 0x17, 0x5b, 0x71, 0x49, 0x62, 0x49, 0x69, 0xb1, 0x04, 0x13, 0xd8, 0x18, 0x28, 0x2f, 0x89,
	0x0d, 0xec, 0x08, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xd9, 0xe1, 0xe9, 0x9c, 0x00,
	0x00, 0x00,
}
