// Code generated by protoc-gen-go. DO NOT EDIT.
// source: close_wallet.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CloseWalletParam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseWalletParam) Reset()         { *m = CloseWalletParam{} }
func (m *CloseWalletParam) String() string { return proto.CompactTextString(m) }
func (*CloseWalletParam) ProtoMessage()    {}
func (*CloseWalletParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_4091e90e469a860a, []int{0}
}

func (m *CloseWalletParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseWalletParam.Unmarshal(m, b)
}
func (m *CloseWalletParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseWalletParam.Marshal(b, m, deterministic)
}
func (m *CloseWalletParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseWalletParam.Merge(m, src)
}
func (m *CloseWalletParam) XXX_Size() int {
	return xxx_messageInfo_CloseWalletParam.Size(m)
}
func (m *CloseWalletParam) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseWalletParam.DiscardUnknown(m)
}

var xxx_messageInfo_CloseWalletParam proto.InternalMessageInfo

type CloseWalletResult struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseWalletResult) Reset()         { *m = CloseWalletResult{} }
func (m *CloseWalletResult) String() string { return proto.CompactTextString(m) }
func (*CloseWalletResult) ProtoMessage()    {}
func (*CloseWalletResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4091e90e469a860a, []int{1}
}

func (m *CloseWalletResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseWalletResult.Unmarshal(m, b)
}
func (m *CloseWalletResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseWalletResult.Marshal(b, m, deterministic)
}
func (m *CloseWalletResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseWalletResult.Merge(m, src)
}
func (m *CloseWalletResult) XXX_Size() int {
	return xxx_messageInfo_CloseWalletResult.Size(m)
}
func (m *CloseWalletResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseWalletResult.DiscardUnknown(m)
}

var xxx_messageInfo_CloseWalletResult proto.InternalMessageInfo

func (m *CloseWalletResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*CloseWalletParam)(nil), "model.CloseWalletParam")
	proto.RegisterType((*CloseWalletResult)(nil), "model.CloseWalletResult")
}

func init() { proto.RegisterFile("close_wallet.proto", fileDescriptor_4091e90e469a860a) }

var fileDescriptor_4091e90e469a860a = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0xce, 0xc9, 0x2f,
	0x4e, 0x8d, 0x2f, 0x4f, 0xcc, 0xc9, 0x49, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x12, 0xe2, 0x12, 0x70, 0x06, 0x49, 0x86, 0x83, 0xe5, 0x02,
	0x12, 0x8b, 0x12, 0x73, 0x95, 0xb4, 0xb9, 0x04, 0x91, 0xc4, 0x82, 0x52, 0x8b, 0x4b, 0x73, 0x4a,
	0x84, 0xc4, 0xb8, 0xd8, 0x8a, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xa0, 0xbc, 0x24, 0x36, 0xb0, 0x71, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x50, 0x42,
	0x32, 0xd1, 0x64, 0x00, 0x00, 0x00,
}
