// Code generated by protoc-gen-go. DO NOT EDIT.
// source: create_new_wallet.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateNewWalletParam struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewWalletParam) Reset()         { *m = CreateNewWalletParam{} }
func (m *CreateNewWalletParam) String() string { return proto.CompactTextString(m) }
func (*CreateNewWalletParam) ProtoMessage()    {}
func (*CreateNewWalletParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_7812a0bf45638a03, []int{0}
}

func (m *CreateNewWalletParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewWalletParam.Unmarshal(m, b)
}
func (m *CreateNewWalletParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewWalletParam.Marshal(b, m, deterministic)
}
func (m *CreateNewWalletParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewWalletParam.Merge(m, src)
}
func (m *CreateNewWalletParam) XXX_Size() int {
	return xxx_messageInfo_CreateNewWalletParam.Size(m)
}
func (m *CreateNewWalletParam) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewWalletParam.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewWalletParam proto.InternalMessageInfo

func (m *CreateNewWalletParam) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *CreateNewWalletParam) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateNewWalletResult struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewWalletResult) Reset()         { *m = CreateNewWalletResult{} }
func (m *CreateNewWalletResult) String() string { return proto.CompactTextString(m) }
func (*CreateNewWalletResult) ProtoMessage()    {}
func (*CreateNewWalletResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_7812a0bf45638a03, []int{1}
}

func (m *CreateNewWalletResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewWalletResult.Unmarshal(m, b)
}
func (m *CreateNewWalletResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewWalletResult.Marshal(b, m, deterministic)
}
func (m *CreateNewWalletResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewWalletResult.Merge(m, src)
}
func (m *CreateNewWalletResult) XXX_Size() int {
	return xxx_messageInfo_CreateNewWalletResult.Size(m)
}
func (m *CreateNewWalletResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewWalletResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewWalletResult proto.InternalMessageInfo

func (m *CreateNewWalletResult) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*CreateNewWalletParam)(nil), "model.CreateNewWalletParam")
	proto.RegisterType((*CreateNewWalletResult)(nil), "model.CreateNewWalletResult")
}

func init() { proto.RegisterFile("create_new_wallet.proto", fileDescriptor_7812a0bf45638a03) }

var fileDescriptor_7812a0bf45638a03 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0x2e, 0x4a, 0x4d,
	0x2c, 0x49, 0x8d, 0xcf, 0x4b, 0x2d, 0x8f, 0x2f, 0x4f, 0xcc, 0xc9, 0x49, 0x2d, 0xd1, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0xf2, 0xe3, 0x12, 0x71, 0x06,
	0xab, 0xf0, 0x4b, 0x2d, 0x0f, 0x07, 0xcb, 0x07, 0x24, 0x16, 0x25, 0xe6, 0x0a, 0x49, 0x71, 0x71,
	0xa4, 0x65, 0xe6, 0xa4, 0xe6, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1,
	0xf9, 0x20, 0xb9, 0x82, 0xc4, 0xe2, 0xe2, 0xf2, 0xfc, 0xa2, 0x14, 0x09, 0x26, 0x88, 0x1c, 0x8c,
	0xaf, 0xa4, 0xcf, 0x25, 0x8a, 0x66, 0x5e, 0x50, 0x6a, 0x71, 0x69, 0x4e, 0x89, 0x90, 0x18, 0x17,
	0x5b, 0x71, 0x49, 0x62, 0x49, 0x69, 0x31, 0xd8, 0x38, 0x8e, 0x20, 0x28, 0x2f, 0x89, 0x0d, 0xec,
	0x1c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x23, 0xc4, 0x89, 0xa9, 0x00, 0x00, 0x00,
}
