// Code generated by protoc-gen-go. DO NOT EDIT.
// source: create_demo_wallet.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateDemoWalletParam struct {
	Filepath             string   `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDemoWalletParam) Reset()         { *m = CreateDemoWalletParam{} }
func (m *CreateDemoWalletParam) String() string { return proto.CompactTextString(m) }
func (*CreateDemoWalletParam) ProtoMessage()    {}
func (*CreateDemoWalletParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_631b2855d0abe543, []int{0}
}

func (m *CreateDemoWalletParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDemoWalletParam.Unmarshal(m, b)
}
func (m *CreateDemoWalletParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDemoWalletParam.Marshal(b, m, deterministic)
}
func (m *CreateDemoWalletParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDemoWalletParam.Merge(m, src)
}
func (m *CreateDemoWalletParam) XXX_Size() int {
	return xxx_messageInfo_CreateDemoWalletParam.Size(m)
}
func (m *CreateDemoWalletParam) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDemoWalletParam.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDemoWalletParam proto.InternalMessageInfo

func (m *CreateDemoWalletParam) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

type CreateDemoWalletResult struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDemoWalletResult) Reset()         { *m = CreateDemoWalletResult{} }
func (m *CreateDemoWalletResult) String() string { return proto.CompactTextString(m) }
func (*CreateDemoWalletResult) ProtoMessage()    {}
func (*CreateDemoWalletResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_631b2855d0abe543, []int{1}
}

func (m *CreateDemoWalletResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDemoWalletResult.Unmarshal(m, b)
}
func (m *CreateDemoWalletResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDemoWalletResult.Marshal(b, m, deterministic)
}
func (m *CreateDemoWalletResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDemoWalletResult.Merge(m, src)
}
func (m *CreateDemoWalletResult) XXX_Size() int {
	return xxx_messageInfo_CreateDemoWalletResult.Size(m)
}
func (m *CreateDemoWalletResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDemoWalletResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDemoWalletResult proto.InternalMessageInfo

func (m *CreateDemoWalletResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateDemoWalletResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateDemoWalletParam)(nil), "model.CreateDemoWalletParam")
	proto.RegisterType((*CreateDemoWalletResult)(nil), "model.CreateDemoWalletResult")
}

func init() { proto.RegisterFile("create_demo_wallet.proto", fileDescriptor_631b2855d0abe543) }

var fileDescriptor_631b2855d0abe543 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0x2e, 0x4a, 0x4d,
	0x2c, 0x49, 0x8d, 0x4f, 0x49, 0xcd, 0xcd, 0x8f, 0x2f, 0x4f, 0xcc, 0xc9, 0x49, 0x2d, 0xd1, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x32, 0xe6, 0x12, 0x75,
	0x06, 0x2b, 0x71, 0x49, 0xcd, 0xcd, 0x0f, 0x07, 0x2b, 0x08, 0x48, 0x2c, 0x4a, 0xcc, 0x15, 0x92,
	0xe2, 0xe2, 0x48, 0xcb, 0xcc, 0x49, 0x2d, 0x48, 0x2c, 0xc9, 0x90, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x82, 0xf3, 0x95, 0xbc, 0xb8, 0xc4, 0xd0, 0x35, 0x05, 0xa5, 0x16, 0x97, 0xe6, 0x94, 0x08,
	0x49, 0x70, 0xb1, 0x17, 0x97, 0x26, 0x27, 0xa7, 0x16, 0x17, 0x83, 0x35, 0x71, 0x04, 0xc1, 0xb8,
	0x42, 0x62, 0x5c, 0x6c, 0xc5, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x12, 0x4c, 0x60, 0xd3, 0xa0, 0xbc,
	0x24, 0x36, 0xb0, 0x73, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x76, 0xba, 0x16, 0x65, 0xaa,
	0x00, 0x00, 0x00,
}
