// Code generated by protoc-gen-go. DO NOT EDIT.
// source: delete_wallet.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteWalletParam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteWalletParam) Reset()         { *m = DeleteWalletParam{} }
func (m *DeleteWalletParam) String() string { return proto.CompactTextString(m) }
func (*DeleteWalletParam) ProtoMessage()    {}
func (*DeleteWalletParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b744b51b33f063a, []int{0}
}

func (m *DeleteWalletParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteWalletParam.Unmarshal(m, b)
}
func (m *DeleteWalletParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteWalletParam.Marshal(b, m, deterministic)
}
func (m *DeleteWalletParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteWalletParam.Merge(m, src)
}
func (m *DeleteWalletParam) XXX_Size() int {
	return xxx_messageInfo_DeleteWalletParam.Size(m)
}
func (m *DeleteWalletParam) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteWalletParam.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteWalletParam proto.InternalMessageInfo

type DeleteWalletResult struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteWalletResult) Reset()         { *m = DeleteWalletResult{} }
func (m *DeleteWalletResult) String() string { return proto.CompactTextString(m) }
func (*DeleteWalletResult) ProtoMessage()    {}
func (*DeleteWalletResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b744b51b33f063a, []int{1}
}

func (m *DeleteWalletResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteWalletResult.Unmarshal(m, b)
}
func (m *DeleteWalletResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteWalletResult.Marshal(b, m, deterministic)
}
func (m *DeleteWalletResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteWalletResult.Merge(m, src)
}
func (m *DeleteWalletResult) XXX_Size() int {
	return xxx_messageInfo_DeleteWalletResult.Size(m)
}
func (m *DeleteWalletResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteWalletResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteWalletResult proto.InternalMessageInfo

func (m *DeleteWalletResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*DeleteWalletParam)(nil), "model.DeleteWalletParam")
	proto.RegisterType((*DeleteWalletResult)(nil), "model.DeleteWalletResult")
}

func init() { proto.RegisterFile("delete_wallet.proto", fileDescriptor_1b744b51b33f063a) }

var fileDescriptor_1b744b51b33f063a = []byte{
	// 103 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x49, 0xcd, 0x49,
	0x2d, 0x49, 0x8d, 0x2f, 0x4f, 0xcc, 0xc9, 0x49, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x12, 0xe6, 0x12, 0x74, 0x01, 0xcb, 0x86, 0x83, 0x25,
	0x03, 0x12, 0x8b, 0x12, 0x73, 0x95, 0x74, 0xb8, 0x84, 0x90, 0x05, 0x83, 0x52, 0x8b, 0x4b, 0x73,
	0x4a, 0x84, 0xc4, 0xb8, 0xd8, 0x8a, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0xa0, 0xbc, 0x24, 0x36, 0xb0, 0x81, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc4,
	0xb1, 0x8f, 0x3d, 0x67, 0x00, 0x00, 0x00,
}
