// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_transfer_fee.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTransferFeeParam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransferFeeParam) Reset()         { *m = GetTransferFeeParam{} }
func (m *GetTransferFeeParam) String() string { return proto.CompactTextString(m) }
func (*GetTransferFeeParam) ProtoMessage()    {}
func (*GetTransferFeeParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_99ed89be5b40355f, []int{0}
}

func (m *GetTransferFeeParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransferFeeParam.Unmarshal(m, b)
}
func (m *GetTransferFeeParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransferFeeParam.Marshal(b, m, deterministic)
}
func (m *GetTransferFeeParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransferFeeParam.Merge(m, src)
}
func (m *GetTransferFeeParam) XXX_Size() int {
	return xxx_messageInfo_GetTransferFeeParam.Size(m)
}
func (m *GetTransferFeeParam) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransferFeeParam.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransferFeeParam proto.InternalMessageInfo

type GetTransferFeeResult struct {
	Fee                  uint64   `protobuf:"varint,1,opt,name=fee,proto3" json:"fee,omitempty"`
	FeeFormat            string   `protobuf:"bytes,2,opt,name=fee_format,json=feeFormat,proto3" json:"fee_format,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransferFeeResult) Reset()         { *m = GetTransferFeeResult{} }
func (m *GetTransferFeeResult) String() string { return proto.CompactTextString(m) }
func (*GetTransferFeeResult) ProtoMessage()    {}
func (*GetTransferFeeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_99ed89be5b40355f, []int{1}
}

func (m *GetTransferFeeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransferFeeResult.Unmarshal(m, b)
}
func (m *GetTransferFeeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransferFeeResult.Marshal(b, m, deterministic)
}
func (m *GetTransferFeeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransferFeeResult.Merge(m, src)
}
func (m *GetTransferFeeResult) XXX_Size() int {
	return xxx_messageInfo_GetTransferFeeResult.Size(m)
}
func (m *GetTransferFeeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransferFeeResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransferFeeResult proto.InternalMessageInfo

func (m *GetTransferFeeResult) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *GetTransferFeeResult) GetFeeFormat() string {
	if m != nil {
		return m.FeeFormat
	}
	return ""
}

func init() {
	proto.RegisterType((*GetTransferFeeParam)(nil), "model.GetTransferFeeParam")
	proto.RegisterType((*GetTransferFeeResult)(nil), "model.GetTransferFeeResult")
}

func init() { proto.RegisterFile("get_transfer_fee.proto", fileDescriptor_99ed89be5b40355f) }

var fileDescriptor_99ed89be5b40355f = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x4f, 0x2d, 0x89,
	0x2f, 0x29, 0x4a, 0xcc, 0x2b, 0x4e, 0x4b, 0x2d, 0x8a, 0x4f, 0x4b, 0x4d, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x12, 0xe5, 0x12, 0x76, 0x4f, 0x2d,
	0x09, 0x81, 0xca, 0xbb, 0xa5, 0xa6, 0x06, 0x24, 0x16, 0x25, 0xe6, 0x2a, 0xb9, 0x73, 0x89, 0xa0,
	0x0a, 0x07, 0xa5, 0x16, 0x97, 0xe6, 0x94, 0x08, 0x09, 0x70, 0x31, 0xa7, 0xa5, 0xa6, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x81, 0x98, 0x42, 0xb2, 0x5c, 0x5c, 0x69, 0xa9, 0xa9, 0xf1, 0x69,
	0xf9, 0x45, 0xb9, 0x89, 0x25, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x9c, 0x69, 0xa9, 0xa9,
	0x6e, 0x60, 0x81, 0x24, 0x36, 0xb0, 0x6d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xcc,
	0xd1, 0xe7, 0x87, 0x00, 0x00, 0x00,
}
