// Code generated by protoc-gen-go. DO NOT EDIT.
// source: is_max_send.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IsMaxSendParam struct {
	Amount               string   `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsMaxSendParam) Reset()         { *m = IsMaxSendParam{} }
func (m *IsMaxSendParam) String() string { return proto.CompactTextString(m) }
func (*IsMaxSendParam) ProtoMessage()    {}
func (*IsMaxSendParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb891f866f23f0e, []int{0}
}

func (m *IsMaxSendParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsMaxSendParam.Unmarshal(m, b)
}
func (m *IsMaxSendParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsMaxSendParam.Marshal(b, m, deterministic)
}
func (m *IsMaxSendParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsMaxSendParam.Merge(m, src)
}
func (m *IsMaxSendParam) XXX_Size() int {
	return xxx_messageInfo_IsMaxSendParam.Size(m)
}
func (m *IsMaxSendParam) XXX_DiscardUnknown() {
	xxx_messageInfo_IsMaxSendParam.DiscardUnknown(m)
}

var xxx_messageInfo_IsMaxSendParam proto.InternalMessageInfo

func (m *IsMaxSendParam) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type IsMaxSendResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsMaxSendResult) Reset()         { *m = IsMaxSendResult{} }
func (m *IsMaxSendResult) String() string { return proto.CompactTextString(m) }
func (*IsMaxSendResult) ProtoMessage()    {}
func (*IsMaxSendResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb891f866f23f0e, []int{1}
}

func (m *IsMaxSendResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsMaxSendResult.Unmarshal(m, b)
}
func (m *IsMaxSendResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsMaxSendResult.Marshal(b, m, deterministic)
}
func (m *IsMaxSendResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsMaxSendResult.Merge(m, src)
}
func (m *IsMaxSendResult) XXX_Size() int {
	return xxx_messageInfo_IsMaxSendResult.Size(m)
}
func (m *IsMaxSendResult) XXX_DiscardUnknown() {
	xxx_messageInfo_IsMaxSendResult.DiscardUnknown(m)
}

var xxx_messageInfo_IsMaxSendResult proto.InternalMessageInfo

func (m *IsMaxSendResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*IsMaxSendParam)(nil), "model.IsMaxSendParam")
	proto.RegisterType((*IsMaxSendResult)(nil), "model.IsMaxSendResult")
}

func init() { proto.RegisterFile("is_max_send.proto", fileDescriptor_deb891f866f23f0e) }

var fileDescriptor_deb891f866f23f0e = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x2c, 0x8e, 0xcf,
	0x4d, 0xac, 0x88, 0x2f, 0x4e, 0xcd, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd,
	0xcd, 0x4f, 0x49, 0xcd, 0x51, 0xd2, 0xe0, 0xe2, 0xf3, 0x2c, 0xf6, 0x4d, 0xac, 0x08, 0x4e, 0xcd,
	0x4b, 0x09, 0x48, 0x2c, 0x4a, 0xcc, 0x15, 0x12, 0xe3, 0x62, 0x4b, 0xcc, 0xcd, 0x2f, 0xcd, 0x2b,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x94, 0x34, 0xb9, 0xf8, 0xe1, 0x2a, 0x83,
	0x52, 0x8b, 0x4b, 0x73, 0x4a, 0x40, 0x4a, 0x8b, 0xc0, 0x2c, 0xb0, 0x52, 0x8e, 0x20, 0x28, 0x2f,
	0x89, 0x0d, 0x6c, 0x85, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x5e, 0x39, 0x24, 0x77, 0x00,
	0x00, 0x00,
}
