// Code generated by protoc-gen-go. DO NOT EDIT.
// source: open_wallet.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpenWalletParam struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenWalletParam) Reset()         { *m = OpenWalletParam{} }
func (m *OpenWalletParam) String() string { return proto.CompactTextString(m) }
func (*OpenWalletParam) ProtoMessage()    {}
func (*OpenWalletParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a7a4cfae5ecd883, []int{0}
}

func (m *OpenWalletParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenWalletParam.Unmarshal(m, b)
}
func (m *OpenWalletParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenWalletParam.Marshal(b, m, deterministic)
}
func (m *OpenWalletParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenWalletParam.Merge(m, src)
}
func (m *OpenWalletParam) XXX_Size() int {
	return xxx_messageInfo_OpenWalletParam.Size(m)
}
func (m *OpenWalletParam) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenWalletParam.DiscardUnknown(m)
}

var xxx_messageInfo_OpenWalletParam proto.InternalMessageInfo

func (m *OpenWalletParam) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *OpenWalletParam) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type OpenWalletResult struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenWalletResult) Reset()         { *m = OpenWalletResult{} }
func (m *OpenWalletResult) String() string { return proto.CompactTextString(m) }
func (*OpenWalletResult) ProtoMessage()    {}
func (*OpenWalletResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a7a4cfae5ecd883, []int{1}
}

func (m *OpenWalletResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenWalletResult.Unmarshal(m, b)
}
func (m *OpenWalletResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenWalletResult.Marshal(b, m, deterministic)
}
func (m *OpenWalletResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenWalletResult.Merge(m, src)
}
func (m *OpenWalletResult) XXX_Size() int {
	return xxx_messageInfo_OpenWalletResult.Size(m)
}
func (m *OpenWalletResult) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenWalletResult.DiscardUnknown(m)
}

var xxx_messageInfo_OpenWalletResult proto.InternalMessageInfo

func (m *OpenWalletResult) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*OpenWalletParam)(nil), "model.OpenWalletParam")
	proto.RegisterType((*OpenWalletResult)(nil), "model.OpenWalletResult")
}

func init() { proto.RegisterFile("open_wallet.proto", fileDescriptor_7a7a4cfae5ecd883) }

var fileDescriptor_7a7a4cfae5ecd883 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x2f, 0x48, 0xcd,
	0x8b, 0x2f, 0x4f, 0xcc, 0xc9, 0x49, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd,
	0xcd, 0x4f, 0x49, 0xcd, 0x51, 0xf2, 0xe4, 0xe2, 0xf7, 0x2f, 0x48, 0xcd, 0x0b, 0x07, 0x4b, 0x05,
	0x24, 0x16, 0x25, 0xe6, 0x0a, 0x49, 0x71, 0x71, 0xa4, 0x65, 0xe6, 0xa4, 0xe6, 0x25, 0xe6, 0xa6,
	0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xf9, 0x20, 0xb9, 0x82, 0xc4, 0xe2, 0xe2, 0xf2,
	0xfc, 0xa2, 0x14, 0x09, 0x26, 0x88, 0x1c, 0x8c, 0xaf, 0xa4, 0xc5, 0x25, 0x80, 0x30, 0x2a, 0x28,
	0xb5, 0xb8, 0x34, 0xa7, 0x44, 0x48, 0x8c, 0x8b, 0xad, 0xb8, 0x24, 0xb1, 0xa4, 0xb4, 0x18, 0x6c,
	0x12, 0x47, 0x10, 0x94, 0x97, 0xc4, 0x06, 0x76, 0x84, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x00,
	0x68, 0xda, 0x09, 0x99, 0x00, 0x00, 0x00,
}
