// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recover_wallet.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RecoverWalletParam struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Data                 string   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	StartHeight          int64    `protobuf:"varint,5,opt,name=startHeight,proto3" json:"startHeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverWalletParam) Reset()         { *m = RecoverWalletParam{} }
func (m *RecoverWalletParam) String() string { return proto.CompactTextString(m) }
func (*RecoverWalletParam) ProtoMessage()    {}
func (*RecoverWalletParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_42b1c2909f1c4cab, []int{0}
}

func (m *RecoverWalletParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverWalletParam.Unmarshal(m, b)
}
func (m *RecoverWalletParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverWalletParam.Marshal(b, m, deterministic)
}
func (m *RecoverWalletParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverWalletParam.Merge(m, src)
}
func (m *RecoverWalletParam) XXX_Size() int {
	return xxx_messageInfo_RecoverWalletParam.Size(m)
}
func (m *RecoverWalletParam) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverWalletParam.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverWalletParam proto.InternalMessageInfo

func (m *RecoverWalletParam) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RecoverWalletParam) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *RecoverWalletParam) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RecoverWalletParam) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *RecoverWalletParam) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

type RecoverWalletResult struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverWalletResult) Reset()         { *m = RecoverWalletResult{} }
func (m *RecoverWalletResult) String() string { return proto.CompactTextString(m) }
func (*RecoverWalletResult) ProtoMessage()    {}
func (*RecoverWalletResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_42b1c2909f1c4cab, []int{1}
}

func (m *RecoverWalletResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverWalletResult.Unmarshal(m, b)
}
func (m *RecoverWalletResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverWalletResult.Marshal(b, m, deterministic)
}
func (m *RecoverWalletResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverWalletResult.Merge(m, src)
}
func (m *RecoverWalletResult) XXX_Size() int {
	return xxx_messageInfo_RecoverWalletResult.Size(m)
}
func (m *RecoverWalletResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverWalletResult.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverWalletResult proto.InternalMessageInfo

func (m *RecoverWalletResult) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*RecoverWalletParam)(nil), "model.RecoverWalletParam")
	proto.RegisterType((*RecoverWalletResult)(nil), "model.RecoverWalletResult")
}

func init() { proto.RegisterFile("recover_wallet.proto", fileDescriptor_42b1c2909f1c4cab) }

var fileDescriptor_42b1c2909f1c4cab = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xbd, 0xaa, 0xc2, 0x40,
	0x10, 0x85, 0xd9, 0x9b, 0x1f, 0x72, 0xd7, 0x6e, 0x14, 0x59, 0xac, 0x42, 0xaa, 0x34, 0xda, 0xf8,
	0x12, 0x96, 0xb2, 0x8d, 0xa5, 0x8c, 0x66, 0xd4, 0xc0, 0xc6, 0x0d, 0xbb, 0x13, 0x83, 0x2f, 0xe2,
	0xf3, 0x4a, 0x36, 0x2a, 0xda, 0xcd, 0x77, 0x3e, 0x38, 0x9c, 0x91, 0x33, 0x47, 0x47, 0x7b, 0x23,
	0xb7, 0xef, 0xd1, 0x18, 0xe2, 0x55, 0xeb, 0x2c, 0x5b, 0x48, 0x1a, 0x5b, 0x91, 0x29, 0x1e, 0x42,
	0x82, 0x1e, 0xfd, 0x2e, 0xe8, 0x2d, 0x3a, 0x6c, 0x00, 0x64, 0xcc, 0xf7, 0x96, 0x94, 0xc8, 0x45,
	0xf9, 0xaf, 0xc3, 0x0d, 0x0b, 0x99, 0x9d, 0x6a, 0x43, 0x57, 0x6c, 0x48, 0xfd, 0x85, 0xfc, 0xc3,
	0x83, 0x6b, 0xd1, 0xfb, 0xde, 0xba, 0x4a, 0x45, 0xa3, 0x7b, 0xf3, 0xd0, 0x55, 0x21, 0xa3, 0x8a,
	0xc7, 0xae, 0xe1, 0x86, 0x5c, 0x4e, 0x3c, 0xa3, 0xe3, 0x0d, 0xd5, 0xe7, 0x0b, 0xab, 0x24, 0x17,
	0x65, 0xa4, 0xbf, 0xa3, 0x62, 0x29, 0xa7, 0x3f, 0xbb, 0x34, 0xf9, 0xce, 0x30, 0xcc, 0x65, 0xea,
	0x19, 0xb9, 0xf3, 0x61, 0x5a, 0xa6, 0x5f, 0x74, 0x48, 0xc3, 0x57, 0xeb, 0x67, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x6e, 0x3e, 0x22, 0x80, 0xed, 0x00, 0x00, 0x00,
}
