// Code generated by protoc-gen-go. DO NOT EDIT.
// source: relay_tx.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RelayTxParam struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelayTxParam) Reset()         { *m = RelayTxParam{} }
func (m *RelayTxParam) String() string { return proto.CompactTextString(m) }
func (*RelayTxParam) ProtoMessage()    {}
func (*RelayTxParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad41b0a618eb9d0c, []int{0}
}

func (m *RelayTxParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelayTxParam.Unmarshal(m, b)
}
func (m *RelayTxParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelayTxParam.Marshal(b, m, deterministic)
}
func (m *RelayTxParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayTxParam.Merge(m, src)
}
func (m *RelayTxParam) XXX_Size() int {
	return xxx_messageInfo_RelayTxParam.Size(m)
}
func (m *RelayTxParam) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayTxParam.DiscardUnknown(m)
}

var xxx_messageInfo_RelayTxParam proto.InternalMessageInfo

func (m *RelayTxParam) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*RelayTxParam)(nil), "model.RelayTxParam")
}

func init() { proto.RegisterFile("relay_tx.proto", fileDescriptor_ad41b0a618eb9d0c) }

var fileDescriptor_ad41b0a618eb9d0c = []byte{
	// 83 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0xcd, 0x49,
	0xac, 0x8c, 0x2f, 0xa9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49,
	0xcd, 0x51, 0x52, 0xe2, 0xe2, 0x09, 0x02, 0x49, 0x84, 0x54, 0x04, 0x24, 0x16, 0x25, 0xe6, 0x0a,
	0x09, 0x71, 0xb1, 0x64, 0x24, 0x16, 0x67, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9,
	0x49, 0x6c, 0x60, 0x1d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xea, 0xd4, 0xe6, 0xb3, 0x43,
	0x00, 0x00, 0x00,
}
