// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rescan.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RescanParam struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RescanParam) Reset()         { *m = RescanParam{} }
func (m *RescanParam) String() string { return proto.CompactTextString(m) }
func (*RescanParam) ProtoMessage()    {}
func (*RescanParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_2792b167634867fa, []int{0}
}

func (m *RescanParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RescanParam.Unmarshal(m, b)
}
func (m *RescanParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RescanParam.Marshal(b, m, deterministic)
}
func (m *RescanParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RescanParam.Merge(m, src)
}
func (m *RescanParam) XXX_Size() int {
	return xxx_messageInfo_RescanParam.Size(m)
}
func (m *RescanParam) XXX_DiscardUnknown() {
	xxx_messageInfo_RescanParam.DiscardUnknown(m)
}

var xxx_messageInfo_RescanParam proto.InternalMessageInfo

func (m *RescanParam) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type RescanResult struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RescanResult) Reset()         { *m = RescanResult{} }
func (m *RescanResult) String() string { return proto.CompactTextString(m) }
func (*RescanResult) ProtoMessage()    {}
func (*RescanResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_2792b167634867fa, []int{1}
}

func (m *RescanResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RescanResult.Unmarshal(m, b)
}
func (m *RescanResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RescanResult.Marshal(b, m, deterministic)
}
func (m *RescanResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RescanResult.Merge(m, src)
}
func (m *RescanResult) XXX_Size() int {
	return xxx_messageInfo_RescanResult.Size(m)
}
func (m *RescanResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RescanResult.DiscardUnknown(m)
}

var xxx_messageInfo_RescanResult proto.InternalMessageInfo

func (m *RescanResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*RescanParam)(nil), "model.RescanParam")
	proto.RegisterType((*RescanResult)(nil), "model.RescanResult")
}

func init() { proto.RegisterFile("rescan.proto", fileDescriptor_2792b167634867fa) }

var fileDescriptor_2792b167634867fa = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0x2d, 0x4e,
	0x4e, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51,
	0x52, 0xe5, 0xe2, 0x0e, 0x02, 0x0b, 0x07, 0x24, 0x16, 0x25, 0xe6, 0x0a, 0x89, 0x71, 0xb1, 0x65,
	0xa4, 0x66, 0xa6, 0x67, 0x94, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x41, 0x79, 0x4a, 0x6a,
	0x5c, 0x3c, 0x10, 0x65, 0x41, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x20, 0x75, 0xc5, 0x25, 0x89, 0x25,
	0xa5, 0xc5, 0x60, 0x75, 0x9c, 0x41, 0x50, 0x5e, 0x12, 0x1b, 0xd8, 0x70, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc5, 0x17, 0xad, 0x2d, 0x6c, 0x00, 0x00, 0x00,
}
