// Code generated by protoc-gen-go. DO NOT EDIT.
// source: set_daemon_address.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetDaemonAddressParam struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDaemonAddressParam) Reset()         { *m = SetDaemonAddressParam{} }
func (m *SetDaemonAddressParam) String() string { return proto.CompactTextString(m) }
func (*SetDaemonAddressParam) ProtoMessage()    {}
func (*SetDaemonAddressParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d8f68c08271af2b, []int{0}
}

func (m *SetDaemonAddressParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDaemonAddressParam.Unmarshal(m, b)
}
func (m *SetDaemonAddressParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDaemonAddressParam.Marshal(b, m, deterministic)
}
func (m *SetDaemonAddressParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDaemonAddressParam.Merge(m, src)
}
func (m *SetDaemonAddressParam) XXX_Size() int {
	return xxx_messageInfo_SetDaemonAddressParam.Size(m)
}
func (m *SetDaemonAddressParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDaemonAddressParam.DiscardUnknown(m)
}

var xxx_messageInfo_SetDaemonAddressParam proto.InternalMessageInfo

func (m *SetDaemonAddressParam) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type SetDaemonAddressResult struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDaemonAddressResult) Reset()         { *m = SetDaemonAddressResult{} }
func (m *SetDaemonAddressResult) String() string { return proto.CompactTextString(m) }
func (*SetDaemonAddressResult) ProtoMessage()    {}
func (*SetDaemonAddressResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d8f68c08271af2b, []int{1}
}

func (m *SetDaemonAddressResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDaemonAddressResult.Unmarshal(m, b)
}
func (m *SetDaemonAddressResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDaemonAddressResult.Marshal(b, m, deterministic)
}
func (m *SetDaemonAddressResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDaemonAddressResult.Merge(m, src)
}
func (m *SetDaemonAddressResult) XXX_Size() int {
	return xxx_messageInfo_SetDaemonAddressResult.Size(m)
}
func (m *SetDaemonAddressResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDaemonAddressResult.DiscardUnknown(m)
}

var xxx_messageInfo_SetDaemonAddressResult proto.InternalMessageInfo

func (m *SetDaemonAddressResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*SetDaemonAddressParam)(nil), "model.SetDaemonAddressParam")
	proto.RegisterType((*SetDaemonAddressResult)(nil), "model.SetDaemonAddressResult")
}

func init() { proto.RegisterFile("set_daemon_address.proto", fileDescriptor_1d8f68c08271af2b) }

var fileDescriptor_1d8f68c08271af2b = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x4e, 0x2d, 0x89,
	0x4f, 0x49, 0x4c, 0xcd, 0xcd, 0xcf, 0x8b, 0x4f, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x32, 0xe4, 0x12, 0x0d,
	0x4e, 0x2d, 0x71, 0x01, 0xab, 0x70, 0x84, 0x28, 0x08, 0x48, 0x2c, 0x4a, 0xcc, 0x15, 0x92, 0xe0,
	0x62, 0x87, 0x6a, 0x90, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x95, 0x0c, 0xb8, 0xc4,
	0xd0, 0xb5, 0x04, 0xa5, 0x16, 0x97, 0xe6, 0x94, 0x08, 0x89, 0x71, 0xb1, 0x15, 0x97, 0x24, 0x96,
	0x94, 0xc2, 0xb4, 0x40, 0x79, 0x49, 0x6c, 0x60, 0x2b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x45, 0x78, 0xbe, 0x78, 0x8e, 0x00, 0x00, 0x00,
}
