// Code generated by protoc-gen-go. DO NOT EDIT.
// source: set_online.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetOnlineParam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOnlineParam) Reset()         { *m = SetOnlineParam{} }
func (m *SetOnlineParam) String() string { return proto.CompactTextString(m) }
func (*SetOnlineParam) ProtoMessage()    {}
func (*SetOnlineParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_951564088bd2b486, []int{0}
}

func (m *SetOnlineParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOnlineParam.Unmarshal(m, b)
}
func (m *SetOnlineParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOnlineParam.Marshal(b, m, deterministic)
}
func (m *SetOnlineParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOnlineParam.Merge(m, src)
}
func (m *SetOnlineParam) XXX_Size() int {
	return xxx_messageInfo_SetOnlineParam.Size(m)
}
func (m *SetOnlineParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOnlineParam.DiscardUnknown(m)
}

var xxx_messageInfo_SetOnlineParam proto.InternalMessageInfo

type SetOnlineResult struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOnlineResult) Reset()         { *m = SetOnlineResult{} }
func (m *SetOnlineResult) String() string { return proto.CompactTextString(m) }
func (*SetOnlineResult) ProtoMessage()    {}
func (*SetOnlineResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_951564088bd2b486, []int{1}
}

func (m *SetOnlineResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOnlineResult.Unmarshal(m, b)
}
func (m *SetOnlineResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOnlineResult.Marshal(b, m, deterministic)
}
func (m *SetOnlineResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOnlineResult.Merge(m, src)
}
func (m *SetOnlineResult) XXX_Size() int {
	return xxx_messageInfo_SetOnlineResult.Size(m)
}
func (m *SetOnlineResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOnlineResult.DiscardUnknown(m)
}

var xxx_messageInfo_SetOnlineResult proto.InternalMessageInfo

func (m *SetOnlineResult) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*SetOnlineParam)(nil), "model.SetOnlineParam")
	proto.RegisterType((*SetOnlineResult)(nil), "model.SetOnlineResult")
}

func init() { proto.RegisterFile("set_online.proto", fileDescriptor_951564088bd2b486) }

var fileDescriptor_951564088bd2b486 = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x4e, 0x2d, 0x89,
	0xcf, 0xcf, 0xcb, 0xc9, 0xcc, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd,
	0x4f, 0x49, 0xcd, 0x51, 0x12, 0xe0, 0xe2, 0x0b, 0x4e, 0x2d, 0xf1, 0x07, 0xcb, 0x04, 0x24, 0x16,
	0x25, 0xe6, 0x2a, 0x69, 0x72, 0xf1, 0xc3, 0x45, 0x82, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0x84, 0xc4,
	0xb8, 0xd8, 0x8a, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x82, 0xa0,
	0xbc, 0x24, 0x36, 0xb0, 0x51, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0x6d, 0xa0, 0x64,
	0x5e, 0x00, 0x00, 0x00,
}
