// Code generated by protoc-gen-go. DO NOT EDIT.
// source: set_cleanup_interval.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetCleanupIntervalParam struct {
	Duration             uint64   `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCleanupIntervalParam) Reset()         { *m = SetCleanupIntervalParam{} }
func (m *SetCleanupIntervalParam) String() string { return proto.CompactTextString(m) }
func (*SetCleanupIntervalParam) ProtoMessage()    {}
func (*SetCleanupIntervalParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b0df0cc2c7eb32, []int{0}
}

func (m *SetCleanupIntervalParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCleanupIntervalParam.Unmarshal(m, b)
}
func (m *SetCleanupIntervalParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCleanupIntervalParam.Marshal(b, m, deterministic)
}
func (m *SetCleanupIntervalParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCleanupIntervalParam.Merge(m, src)
}
func (m *SetCleanupIntervalParam) XXX_Size() int {
	return xxx_messageInfo_SetCleanupIntervalParam.Size(m)
}
func (m *SetCleanupIntervalParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCleanupIntervalParam.DiscardUnknown(m)
}

var xxx_messageInfo_SetCleanupIntervalParam proto.InternalMessageInfo

func (m *SetCleanupIntervalParam) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type SetCleanupIntervalResult struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCleanupIntervalResult) Reset()         { *m = SetCleanupIntervalResult{} }
func (m *SetCleanupIntervalResult) String() string { return proto.CompactTextString(m) }
func (*SetCleanupIntervalResult) ProtoMessage()    {}
func (*SetCleanupIntervalResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b0df0cc2c7eb32, []int{1}
}

func (m *SetCleanupIntervalResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCleanupIntervalResult.Unmarshal(m, b)
}
func (m *SetCleanupIntervalResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCleanupIntervalResult.Marshal(b, m, deterministic)
}
func (m *SetCleanupIntervalResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCleanupIntervalResult.Merge(m, src)
}
func (m *SetCleanupIntervalResult) XXX_Size() int {
	return xxx_messageInfo_SetCleanupIntervalResult.Size(m)
}
func (m *SetCleanupIntervalResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCleanupIntervalResult.DiscardUnknown(m)
}

var xxx_messageInfo_SetCleanupIntervalResult proto.InternalMessageInfo

func (m *SetCleanupIntervalResult) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*SetCleanupIntervalParam)(nil), "model.SetCleanupIntervalParam")
	proto.RegisterType((*SetCleanupIntervalResult)(nil), "model.SetCleanupIntervalResult")
}

func init() { proto.RegisterFile("set_cleanup_interval.proto", fileDescriptor_f4b0df0cc2c7eb32) }

var fileDescriptor_f4b0df0cc2c7eb32 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x4e, 0x2d, 0x89,
	0x4f, 0xce, 0x49, 0x4d, 0xcc, 0x2b, 0x2d, 0x88, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0x2a, 0x4b, 0xcc,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x32, 0xe5,
	0x12, 0x0f, 0x4e, 0x2d, 0x71, 0x86, 0xa8, 0xf1, 0x84, 0x2a, 0x09, 0x48, 0x2c, 0x4a, 0xcc, 0x15,
	0x92, 0xe2, 0xe2, 0x48, 0x29, 0x2d, 0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0x93, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x09, 0x82, 0xf3, 0x95, 0x8c, 0xb8, 0x24, 0x30, 0xb5, 0x05, 0xa5, 0x16, 0x97, 0xe6, 0x94,
	0x08, 0x89, 0x71, 0xb1, 0x15, 0x97, 0x24, 0x96, 0x94, 0x16, 0x83, 0x75, 0x71, 0x04, 0x41, 0x79,
	0x49, 0x6c, 0x60, 0x8b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x30, 0xf5, 0x6e, 0x96,
	0x00, 0x00, 0x00,
}
