// Code generated by protoc-gen-go. DO NOT EDIT.
// source: set_offline.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetOfflineParam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOfflineParam) Reset()         { *m = SetOfflineParam{} }
func (m *SetOfflineParam) String() string { return proto.CompactTextString(m) }
func (*SetOfflineParam) ProtoMessage()    {}
func (*SetOfflineParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_653c88f11e0e9089, []int{0}
}

func (m *SetOfflineParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOfflineParam.Unmarshal(m, b)
}
func (m *SetOfflineParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOfflineParam.Marshal(b, m, deterministic)
}
func (m *SetOfflineParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOfflineParam.Merge(m, src)
}
func (m *SetOfflineParam) XXX_Size() int {
	return xxx_messageInfo_SetOfflineParam.Size(m)
}
func (m *SetOfflineParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOfflineParam.DiscardUnknown(m)
}

var xxx_messageInfo_SetOfflineParam proto.InternalMessageInfo

type SetOfflineResult struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOfflineResult) Reset()         { *m = SetOfflineResult{} }
func (m *SetOfflineResult) String() string { return proto.CompactTextString(m) }
func (*SetOfflineResult) ProtoMessage()    {}
func (*SetOfflineResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_653c88f11e0e9089, []int{1}
}

func (m *SetOfflineResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOfflineResult.Unmarshal(m, b)
}
func (m *SetOfflineResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOfflineResult.Marshal(b, m, deterministic)
}
func (m *SetOfflineResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOfflineResult.Merge(m, src)
}
func (m *SetOfflineResult) XXX_Size() int {
	return xxx_messageInfo_SetOfflineResult.Size(m)
}
func (m *SetOfflineResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOfflineResult.DiscardUnknown(m)
}

var xxx_messageInfo_SetOfflineResult proto.InternalMessageInfo

func (m *SetOfflineResult) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*SetOfflineParam)(nil), "model.SetOfflineParam")
	proto.RegisterType((*SetOfflineResult)(nil), "model.SetOfflineResult")
}

func init() { proto.RegisterFile("set_offline.proto", fileDescriptor_653c88f11e0e9089) }

var fileDescriptor_653c88f11e0e9089 = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x4e, 0x2d, 0x89,
	0xcf, 0x4f, 0x4b, 0xcb, 0xc9, 0xcc, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd,
	0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x12, 0xe4, 0xe2, 0x0f, 0x4e, 0x2d, 0xf1, 0x87, 0x48, 0x05, 0x24,
	0x16, 0x25, 0xe6, 0x2a, 0x69, 0x71, 0x09, 0x20, 0x84, 0x82, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0x84,
	0xc4, 0xb8, 0xd8, 0x8a, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x82,
	0xa0, 0xbc, 0x24, 0x36, 0xb0, 0x61, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x56, 0xd1, 0xd6,
	0x51, 0x61, 0x00, 0x00, 0x00,
}
