// Code generated by protoc-gen-go. DO NOT EDIT.
// source: set_mode.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetModeParam struct {
	Mode                 bool     `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetModeParam) Reset()         { *m = SetModeParam{} }
func (m *SetModeParam) String() string { return proto.CompactTextString(m) }
func (*SetModeParam) ProtoMessage()    {}
func (*SetModeParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf9e0f089ac6dcfc, []int{0}
}

func (m *SetModeParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetModeParam.Unmarshal(m, b)
}
func (m *SetModeParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetModeParam.Marshal(b, m, deterministic)
}
func (m *SetModeParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetModeParam.Merge(m, src)
}
func (m *SetModeParam) XXX_Size() int {
	return xxx_messageInfo_SetModeParam.Size(m)
}
func (m *SetModeParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SetModeParam.DiscardUnknown(m)
}

var xxx_messageInfo_SetModeParam proto.InternalMessageInfo

func (m *SetModeParam) GetMode() bool {
	if m != nil {
		return m.Mode
	}
	return false
}

type SetModeResult struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetModeResult) Reset()         { *m = SetModeResult{} }
func (m *SetModeResult) String() string { return proto.CompactTextString(m) }
func (*SetModeResult) ProtoMessage()    {}
func (*SetModeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf9e0f089ac6dcfc, []int{1}
}

func (m *SetModeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetModeResult.Unmarshal(m, b)
}
func (m *SetModeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetModeResult.Marshal(b, m, deterministic)
}
func (m *SetModeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetModeResult.Merge(m, src)
}
func (m *SetModeResult) XXX_Size() int {
	return xxx_messageInfo_SetModeResult.Size(m)
}
func (m *SetModeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SetModeResult.DiscardUnknown(m)
}

var xxx_messageInfo_SetModeResult proto.InternalMessageInfo

func (m *SetModeResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*SetModeParam)(nil), "model.SetModeParam")
	proto.RegisterType((*SetModeResult)(nil), "model.SetModeResult")
}

func init() { proto.RegisterFile("set_mode.proto", fileDescriptor_bf9e0f089ac6dcfc) }

var fileDescriptor_bf9e0f089ac6dcfc = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4e, 0x2d, 0x89,
	0xcf, 0xcd, 0x4f, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0xb1, 0x73, 0x94,
	0x94, 0xb8, 0x78, 0x82, 0x53, 0x4b, 0x7c, 0xf3, 0x53, 0x52, 0x03, 0x12, 0x8b, 0x12, 0x73, 0x85,
	0x84, 0xb8, 0x58, 0x40, 0x12, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x60, 0xb6, 0x92, 0x3a,
	0x17, 0x2f, 0x54, 0x4d, 0x50, 0x6a, 0x71, 0x69, 0x4e, 0x89, 0x90, 0x18, 0x17, 0x5b, 0x71, 0x49,
	0x62, 0x49, 0x69, 0x31, 0x58, 0x19, 0x67, 0x10, 0x94, 0x97, 0xc4, 0x06, 0x36, 0xda, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x59, 0xcd, 0x3f, 0x9a, 0x6c, 0x00, 0x00, 0x00,
}
