// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transfers_everything.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransfersEverythingParam struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Fee                  uint64   `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	Mixin                uint64   `protobuf:"varint,3,opt,name=mixin,proto3" json:"mixin,omitempty"`
	UnlockTime           uint64   `protobuf:"varint,4,opt,name=unlock_time,json=unlockTime,proto3" json:"unlock_time,omitempty"`
	PaymentId            string   `protobuf:"bytes,5,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransfersEverythingParam) Reset()         { *m = TransfersEverythingParam{} }
func (m *TransfersEverythingParam) String() string { return proto.CompactTextString(m) }
func (*TransfersEverythingParam) ProtoMessage()    {}
func (*TransfersEverythingParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f506fe91dc5d1fb, []int{0}
}

func (m *TransfersEverythingParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransfersEverythingParam.Unmarshal(m, b)
}
func (m *TransfersEverythingParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransfersEverythingParam.Marshal(b, m, deterministic)
}
func (m *TransfersEverythingParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransfersEverythingParam.Merge(m, src)
}
func (m *TransfersEverythingParam) XXX_Size() int {
	return xxx_messageInfo_TransfersEverythingParam.Size(m)
}
func (m *TransfersEverythingParam) XXX_DiscardUnknown() {
	xxx_messageInfo_TransfersEverythingParam.DiscardUnknown(m)
}

var xxx_messageInfo_TransfersEverythingParam proto.InternalMessageInfo

func (m *TransfersEverythingParam) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TransfersEverythingParam) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *TransfersEverythingParam) GetMixin() uint64 {
	if m != nil {
		return m.Mixin
	}
	return 0
}

func (m *TransfersEverythingParam) GetUnlockTime() uint64 {
	if m != nil {
		return m.UnlockTime
	}
	return 0
}

func (m *TransfersEverythingParam) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

func init() {
	proto.RegisterType((*TransfersEverythingParam)(nil), "model.TransfersEverythingParam")
}

func init() { proto.RegisterFile("transfers_everything.proto", fileDescriptor_7f506fe91dc5d1fb) }

var fileDescriptor_7f506fe91dc5d1fb = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0xc1, 0x8a, 0xc2, 0x30,
	0x10, 0x40, 0xc9, 0xb6, 0xdd, 0xa5, 0xb3, 0x17, 0x09, 0x1e, 0x06, 0x41, 0x2c, 0x9e, 0x7a, 0xf2,
	0xe2, 0x37, 0x78, 0xf0, 0x26, 0xa5, 0xf7, 0x12, 0xcd, 0x54, 0x83, 0x4d, 0x52, 0x92, 0x28, 0xf6,
	0x5f, 0xfc, 0x58, 0x31, 0xb5, 0xde, 0xe6, 0xbd, 0x79, 0x30, 0x03, 0x8b, 0xe0, 0x84, 0xf1, 0x2d,
	0x39, 0xdf, 0xd0, 0x9d, 0xdc, 0x10, 0x2e, 0xca, 0x9c, 0x37, 0xbd, 0xb3, 0xc1, 0xf2, 0x4c, 0x5b,
	0x49, 0xdd, 0xfa, 0xc9, 0x00, 0xeb, 0xa9, 0xda, 0x7d, 0xa3, 0x83, 0x70, 0x42, 0x73, 0x84, 0x3f,
	0x21, 0xa5, 0x23, 0xef, 0x91, 0x15, 0xac, 0xcc, 0xab, 0x09, 0xf9, 0x0c, 0x92, 0x96, 0x08, 0x7f,
	0x0a, 0x56, 0xa6, 0xd5, 0x7b, 0xe4, 0x73, 0xc8, 0xb4, 0x7a, 0x28, 0x83, 0x49, 0x74, 0x23, 0xf0,
	0x15, 0xfc, 0xdf, 0x4c, 0x67, 0x4f, 0xd7, 0x26, 0x28, 0x4d, 0x98, 0xc6, 0x1d, 0x8c, 0xaa, 0x56,
	0x9a, 0xf8, 0x12, 0xa0, 0x17, 0x83, 0x26, 0x13, 0x1a, 0x25, 0x31, 0x8b, 0x57, 0xf2, 0x8f, 0xd9,
	0xcb, 0xe3, 0x6f, 0x7c, 0x76, 0xfb, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x52, 0xd6, 0xe8, 0x7d, 0xca,
	0x00, 0x00, 0x00,
}
