// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transfers.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransfersParam struct {
	Destinations         []*Destination `protobuf:"bytes,1,rep,name=Destinations,proto3" json:"Destinations,omitempty"`
	Fee                  uint64         `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	Mixin                uint64         `protobuf:"varint,3,opt,name=mixin,proto3" json:"mixin,omitempty"`
	UnlockTime           uint64         `protobuf:"varint,4,opt,name=unlock_time,json=unlockTime,proto3" json:"unlock_time,omitempty"`
	PaymentId            string         `protobuf:"bytes,5,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	GetTxKey             bool           `protobuf:"varint,6,opt,name=get_tx_key,json=getTxKey,proto3" json:"get_tx_key,omitempty"`
	Priority             uint64         `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	GetTxHex             bool           `protobuf:"varint,8,opt,name=get_tx_hex,json=getTxHex,proto3" json:"get_tx_hex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransfersParam) Reset()         { *m = TransfersParam{} }
func (m *TransfersParam) String() string { return proto.CompactTextString(m) }
func (*TransfersParam) ProtoMessage()    {}
func (*TransfersParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_61401ad0522767fa, []int{0}
}

func (m *TransfersParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransfersParam.Unmarshal(m, b)
}
func (m *TransfersParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransfersParam.Marshal(b, m, deterministic)
}
func (m *TransfersParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransfersParam.Merge(m, src)
}
func (m *TransfersParam) XXX_Size() int {
	return xxx_messageInfo_TransfersParam.Size(m)
}
func (m *TransfersParam) XXX_DiscardUnknown() {
	xxx_messageInfo_TransfersParam.DiscardUnknown(m)
}

var xxx_messageInfo_TransfersParam proto.InternalMessageInfo

func (m *TransfersParam) GetDestinations() []*Destination {
	if m != nil {
		return m.Destinations
	}
	return nil
}

func (m *TransfersParam) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *TransfersParam) GetMixin() uint64 {
	if m != nil {
		return m.Mixin
	}
	return 0
}

func (m *TransfersParam) GetUnlockTime() uint64 {
	if m != nil {
		return m.UnlockTime
	}
	return 0
}

func (m *TransfersParam) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

func (m *TransfersParam) GetGetTxKey() bool {
	if m != nil {
		return m.GetTxKey
	}
	return false
}

func (m *TransfersParam) GetPriority() uint64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *TransfersParam) GetGetTxHex() bool {
	if m != nil {
		return m.GetTxHex
	}
	return false
}

func init() {
	proto.RegisterType((*TransfersParam)(nil), "model.TransfersParam")
}

func init() { proto.RegisterFile("transfers.proto", fileDescriptor_61401ad0522767fa) }

var fileDescriptor_61401ad0522767fa = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbd, 0x4e, 0xc3, 0x40,
	0x10, 0x84, 0xe5, 0x38, 0x0e, 0xce, 0x06, 0xf1, 0xb3, 0xa2, 0x38, 0x45, 0x20, 0x2c, 0x2a, 0x57,
	0x2e, 0x40, 0xe2, 0x09, 0x28, 0x40, 0x34, 0xc8, 0x72, 0x6f, 0x19, 0xbc, 0x09, 0xab, 0xe4, 0xee,
	0xac, 0xf3, 0x22, 0x9d, 0xdf, 0x80, 0xc7, 0x46, 0x9c, 0xf9, 0x71, 0xba, 0x9d, 0x99, 0x6f, 0xa6,
	0x58, 0x38, 0x15, 0xd7, 0x98, 0x7e, 0x43, 0xae, 0x2f, 0x3a, 0x67, 0xc5, 0x62, 0xa2, 0x6d, 0x4b,
	0xfb, 0xf5, 0x79, 0x4b, 0xbd, 0xb0, 0x69, 0x84, 0xad, 0x19, 0x93, 0x9b, 0xcf, 0x19, 0x9c, 0x54,
	0xbf, 0xf4, 0x4b, 0xe3, 0x1a, 0x8d, 0xf7, 0x70, 0xfc, 0xf0, 0xcf, 0xf5, 0x2a, 0xca, 0xe2, 0x7c,
	0x75, 0x8b, 0x45, 0xd8, 0x28, 0x26, 0x51, 0x79, 0xc0, 0xe1, 0x19, 0xc4, 0x1b, 0x22, 0x35, 0xcb,
	0xa2, 0x7c, 0x5e, 0x7e, 0x9f, 0x78, 0x01, 0x89, 0x66, 0xcf, 0x46, 0xc5, 0xc1, 0x1b, 0x05, 0x5e,
	0xc3, 0xea, 0xc3, 0xec, 0xed, 0xdb, 0xae, 0x16, 0xd6, 0xa4, 0xe6, 0x21, 0x83, 0xd1, 0xaa, 0x58,
	0x13, 0x5e, 0x01, 0x74, 0xcd, 0xa0, 0xc9, 0x48, 0xcd, 0xad, 0x4a, 0xb2, 0x28, 0x5f, 0x96, 0xcb,
	0x1f, 0xe7, 0xa9, 0xc5, 0x4b, 0x80, 0x2d, 0x49, 0x2d, 0xbe, 0xde, 0xd1, 0xa0, 0x16, 0x59, 0x94,
	0xa7, 0x65, 0xba, 0x25, 0xa9, 0xfc, 0x33, 0x0d, 0xb8, 0x86, 0xb4, 0x73, 0x6c, 0x1d, 0xcb, 0xa0,
	0x8e, 0xc2, 0xf4, 0x9f, 0x9e, 0x34, 0xdf, 0xc9, 0xab, 0x74, 0xd2, 0x7c, 0x24, 0xff, 0xba, 0x08,
	0x1f, 0xb9, 0xfb, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xbc, 0xb1, 0xc7, 0x3e, 0x01, 0x00, 0x00,
}
