// Code generated by protoc-gen-go. DO NOT EDIT.
// source: validate_address.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValidateAddressParam struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateAddressParam) Reset()         { *m = ValidateAddressParam{} }
func (m *ValidateAddressParam) String() string { return proto.CompactTextString(m) }
func (*ValidateAddressParam) ProtoMessage()    {}
func (*ValidateAddressParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_426d26f2688c4651, []int{0}
}

func (m *ValidateAddressParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateAddressParam.Unmarshal(m, b)
}
func (m *ValidateAddressParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateAddressParam.Marshal(b, m, deterministic)
}
func (m *ValidateAddressParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateAddressParam.Merge(m, src)
}
func (m *ValidateAddressParam) XXX_Size() int {
	return xxx_messageInfo_ValidateAddressParam.Size(m)
}
func (m *ValidateAddressParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateAddressParam.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateAddressParam proto.InternalMessageInfo

func (m *ValidateAddressParam) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ValidateAddressResult struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateAddressResult) Reset()         { *m = ValidateAddressResult{} }
func (m *ValidateAddressResult) String() string { return proto.CompactTextString(m) }
func (*ValidateAddressResult) ProtoMessage()    {}
func (*ValidateAddressResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_426d26f2688c4651, []int{1}
}

func (m *ValidateAddressResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateAddressResult.Unmarshal(m, b)
}
func (m *ValidateAddressResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateAddressResult.Marshal(b, m, deterministic)
}
func (m *ValidateAddressResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateAddressResult.Merge(m, src)
}
func (m *ValidateAddressResult) XXX_Size() int {
	return xxx_messageInfo_ValidateAddressResult.Size(m)
}
func (m *ValidateAddressResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateAddressResult.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateAddressResult proto.InternalMessageInfo

func (m *ValidateAddressResult) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *ValidateAddressResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*ValidateAddressParam)(nil), "model.ValidateAddressParam")
	proto.RegisterType((*ValidateAddressResult)(nil), "model.ValidateAddressResult")
}

func init() { proto.RegisterFile("validate_address.proto", fileDescriptor_426d26f2688c4651) }

var fileDescriptor_426d26f2688c4651 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4b, 0xcc, 0xc9,
	0x4c, 0x49, 0x2c, 0x49, 0x8d, 0x4f, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0xd6, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x32, 0xe0, 0x12, 0x09, 0x83, 0x2a,
	0x70, 0x84, 0xc8, 0x07, 0x24, 0x16, 0x25, 0xe6, 0x0a, 0x49, 0x70, 0xb1, 0x43, 0xd5, 0x4b, 0x30,
	0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x4a, 0xae, 0x5c, 0xa2, 0x68, 0x3a, 0x82, 0x52, 0x8b,
	0x4b, 0x73, 0x4a, 0x84, 0x44, 0xb8, 0x58, 0xc1, 0x76, 0x81, 0x35, 0x70, 0x04, 0x41, 0x38, 0x42,
	0x62, 0x5c, 0x6c, 0xc5, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x12, 0x4c, 0x60, 0x73, 0xa0, 0xbc, 0x24,
	0x36, 0xb0, 0x33, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x4f, 0x20, 0x95, 0xa0, 0x00,
	0x00, 0x00,
}
