// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet_state.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WalletStateParam struct {
	AppSettings          *AppSettings `protobuf:"bytes,1,opt,name=app_settings,json=appSettings,proto3" json:"app_settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *WalletStateParam) Reset()         { *m = WalletStateParam{} }
func (m *WalletStateParam) String() string { return proto.CompactTextString(m) }
func (*WalletStateParam) ProtoMessage()    {}
func (*WalletStateParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0a2946e9ad6af9d, []int{0}
}

func (m *WalletStateParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletStateParam.Unmarshal(m, b)
}
func (m *WalletStateParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletStateParam.Marshal(b, m, deterministic)
}
func (m *WalletStateParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletStateParam.Merge(m, src)
}
func (m *WalletStateParam) XXX_Size() int {
	return xxx_messageInfo_WalletStateParam.Size(m)
}
func (m *WalletStateParam) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletStateParam.DiscardUnknown(m)
}

var xxx_messageInfo_WalletStateParam proto.InternalMessageInfo

func (m *WalletStateParam) GetAppSettings() *AppSettings {
	if m != nil {
		return m.AppSettings
	}
	return nil
}

type WalletState struct {
	Mode                 bool     `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Height               uint64   `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	TopoHeight           int64    `protobuf:"varint,4,opt,name=topo_height,json=topoHeight,proto3" json:"topo_height,omitempty"`
	DaemonAddress        string   `protobuf:"bytes,5,opt,name=daemon_address,json=daemonAddress,proto3" json:"daemon_address,omitempty"`
	DaemonHeight         uint64   `protobuf:"varint,6,opt,name=daemon_height,json=daemonHeight,proto3" json:"daemon_height,omitempty"`
	DaemonTopoHeight     int64    `protobuf:"varint,7,opt,name=daemon_topo_height,json=daemonTopoHeight,proto3" json:"daemon_topo_height,omitempty"`
	MatureBalance        uint64   `protobuf:"varint,8,opt,name=mature_balance,json=matureBalance,proto3" json:"mature_balance,omitempty"`
	LockedBalance        uint64   `protobuf:"varint,9,opt,name=locked_balance,json=lockedBalance,proto3" json:"locked_balance,omitempty"`
	Balance              uint64   `protobuf:"varint,10,opt,name=balance,proto3" json:"balance,omitempty"`
	Price                float64  `protobuf:"fixed64,11,opt,name=price,proto3" json:"price,omitempty"`
	WalletPath           string   `protobuf:"bytes,12,opt,name=wallet_path,json=walletPath,proto3" json:"wallet_path,omitempty"`
	Seed                 string   `protobuf:"bytes,13,opt,name=seed,proto3" json:"seed,omitempty"`
	SpendKey             string   `protobuf:"bytes,14,opt,name=spend_key,json=spendKey,proto3" json:"spend_key,omitempty"`
	ViewKey              string   `protobuf:"bytes,15,opt,name=view_key,json=viewKey,proto3" json:"view_key,omitempty"`
	IsViewOnly           bool     `protobuf:"varint,16,opt,name=is_view_only,json=isViewOnly,proto3" json:"is_view_only,omitempty"`
	TxFee                uint64   `protobuf:"varint,17,opt,name=tx_fee,json=txFee,proto3" json:"tx_fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletState) Reset()         { *m = WalletState{} }
func (m *WalletState) String() string { return proto.CompactTextString(m) }
func (*WalletState) ProtoMessage()    {}
func (*WalletState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0a2946e9ad6af9d, []int{1}
}

func (m *WalletState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletState.Unmarshal(m, b)
}
func (m *WalletState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletState.Marshal(b, m, deterministic)
}
func (m *WalletState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletState.Merge(m, src)
}
func (m *WalletState) XXX_Size() int {
	return xxx_messageInfo_WalletState.Size(m)
}
func (m *WalletState) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletState.DiscardUnknown(m)
}

var xxx_messageInfo_WalletState proto.InternalMessageInfo

func (m *WalletState) GetMode() bool {
	if m != nil {
		return m.Mode
	}
	return false
}

func (m *WalletState) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *WalletState) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *WalletState) GetTopoHeight() int64 {
	if m != nil {
		return m.TopoHeight
	}
	return 0
}

func (m *WalletState) GetDaemonAddress() string {
	if m != nil {
		return m.DaemonAddress
	}
	return ""
}

func (m *WalletState) GetDaemonHeight() uint64 {
	if m != nil {
		return m.DaemonHeight
	}
	return 0
}

func (m *WalletState) GetDaemonTopoHeight() int64 {
	if m != nil {
		return m.DaemonTopoHeight
	}
	return 0
}

func (m *WalletState) GetMatureBalance() uint64 {
	if m != nil {
		return m.MatureBalance
	}
	return 0
}

func (m *WalletState) GetLockedBalance() uint64 {
	if m != nil {
		return m.LockedBalance
	}
	return 0
}

func (m *WalletState) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *WalletState) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *WalletState) GetWalletPath() string {
	if m != nil {
		return m.WalletPath
	}
	return ""
}

func (m *WalletState) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

func (m *WalletState) GetSpendKey() string {
	if m != nil {
		return m.SpendKey
	}
	return ""
}

func (m *WalletState) GetViewKey() string {
	if m != nil {
		return m.ViewKey
	}
	return ""
}

func (m *WalletState) GetIsViewOnly() bool {
	if m != nil {
		return m.IsViewOnly
	}
	return false
}

func (m *WalletState) GetTxFee() uint64 {
	if m != nil {
		return m.TxFee
	}
	return 0
}

func init() {
	proto.RegisterType((*WalletStateParam)(nil), "model.WalletStateParam")
	proto.RegisterType((*WalletState)(nil), "model.WalletState")
}

func init() { proto.RegisterFile("wallet_state.proto", fileDescriptor_e0a2946e9ad6af9d) }

var fileDescriptor_e0a2946e9ad6af9d = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x41, 0x8f, 0xd3, 0x30,
	0x10, 0x85, 0x15, 0x36, 0x49, 0xd3, 0x49, 0xba, 0x74, 0x2d, 0x40, 0x06, 0x0e, 0x44, 0x8b, 0x90,
	0x72, 0x40, 0x3d, 0x80, 0xf8, 0x01, 0xcb, 0x01, 0x81, 0x38, 0xb0, 0xca, 0x22, 0x38, 0x5a, 0xde,
	0x66, 0xd8, 0x44, 0x9b, 0xc4, 0x56, 0x6c, 0x68, 0xf3, 0x37, 0xf8, 0xc5, 0xc8, 0x63, 0x07, 0xca,
	0xcd, 0xef, 0x7d, 0xcf, 0x6f, 0x5a, 0x4f, 0x80, 0x1d, 0x64, 0xdf, 0xa3, 0x15, 0xc6, 0x4a, 0x8b,
	0x3b, 0x3d, 0x29, 0xab, 0x58, 0x32, 0xa8, 0x06, 0xfb, 0x67, 0x17, 0x52, 0x6b, 0x83, 0xd6, 0x76,
	0xe3, 0x9d, 0xf1, 0xe4, 0xf2, 0x13, 0x6c, 0xbf, 0x53, 0xfe, 0xc6, 0xc5, 0xaf, 0xe5, 0x24, 0x07,
	0xf6, 0x0e, 0x0a, 0xa9, 0xb5, 0x58, 0x92, 0x3c, 0x2a, 0xa3, 0x2a, 0x7f, 0xc3, 0x76, 0x54, 0xb2,
	0xbb, 0xd2, 0xfa, 0x26, 0x90, 0x3a, 0x97, 0xff, 0xc4, 0xe5, 0xef, 0x18, 0xf2, 0x93, 0x2e, 0xc6,
	0x20, 0x76, 0x37, 0xe8, 0x7a, 0x56, 0xd3, 0x99, 0x71, 0x58, 0xc9, 0xa6, 0x99, 0xd0, 0x18, 0xfe,
	0xa0, 0x8c, 0xaa, 0x75, 0xbd, 0x48, 0xf6, 0x04, 0xd2, 0x16, 0xbb, 0xbb, 0xd6, 0xf2, 0xb3, 0x32,
	0xaa, 0xe2, 0x3a, 0x28, 0xf6, 0x02, 0x72, 0xab, 0xb4, 0x12, 0x01, 0xc6, 0x65, 0x54, 0x9d, 0xd5,
	0xe0, 0xac, 0x8f, 0x3e, 0xf0, 0x0a, 0xce, 0x1b, 0x89, 0x83, 0x1a, 0xc5, 0xd2, 0x9c, 0x50, 0xf3,
	0xc6, 0xbb, 0x57, 0xa1, 0xff, 0x25, 0x04, 0x63, 0x69, 0x4a, 0x69, 0x4c, 0xe1, 0xcd, 0xd0, 0xf5,
	0x1a, 0x58, 0x08, 0x9d, 0xce, 0x5c, 0xd1, 0xcc, 0xad, 0x27, 0x5f, 0xff, 0x9b, 0x3c, 0x48, 0xfb,
	0x73, 0x42, 0x71, 0x2b, 0x7b, 0x39, 0xee, 0x91, 0x67, 0xd4, 0xb9, 0xf1, 0xee, 0x7b, 0x6f, 0xba,
	0x58, 0xaf, 0xf6, 0xf7, 0xd8, 0xfc, 0x8d, 0xad, 0x7d, 0xcc, 0xbb, 0x4b, 0x8c, 0xc3, 0x6a, 0xe1,
	0x40, 0x7c, 0x91, 0xec, 0x11, 0x24, 0x7a, 0xea, 0xf6, 0xc8, 0xf3, 0x32, 0xaa, 0xa2, 0xda, 0x0b,
	0xf7, 0x30, 0x61, 0xd3, 0x5a, 0xda, 0x96, 0x17, 0xf4, 0xa7, 0xc1, 0x5b, 0xd7, 0xd2, 0xb6, 0xee,
	0xfd, 0x0d, 0x62, 0xc3, 0x37, 0x44, 0xe8, 0xcc, 0x9e, 0xc3, 0xda, 0x68, 0x1c, 0x1b, 0x71, 0x8f,
	0x33, 0x3f, 0x27, 0x90, 0x91, 0xf1, 0x19, 0x67, 0xf6, 0x14, 0xb2, 0x5f, 0x1d, 0x1e, 0x88, 0x3d,
	0xf4, 0xdb, 0x71, 0xda, 0xa1, 0x12, 0x8a, 0xce, 0x08, 0xa2, 0x6a, 0xec, 0x67, 0xbe, 0xa5, 0x9d,
	0x42, 0x67, 0xbe, 0x75, 0x78, 0xf8, 0x32, 0xf6, 0x33, 0x7b, 0x0c, 0xa9, 0x3d, 0x8a, 0x1f, 0x88,
	0xfc, 0x82, 0x7e, 0x7d, 0x62, 0x8f, 0x1f, 0x10, 0x6f, 0x53, 0xfa, 0xcc, 0xde, 0xfe, 0x09, 0x00,
	0x00, 0xff, 0xff, 0xe4, 0x2d, 0x73, 0xd7, 0x96, 0x02, 0x00, 0x00,
}
